[package]
name = "openttd-relayrl-example"
version = "0.1.0"
edition = "2024"
publish = false
description = "RelayRL system-of-systems example targeting OpenTTD."

[features]
default = []
native-openttd = []

[dependencies]
relayrl = { path = "../../crates/relayrl", default-features = false, features = ["client"] }
relayrl_env_trait = { workspace = true }
relayrl_types = { workspace = true }

burn-ndarray = { workspace = true }
burn-tensor = { workspace = true }

serde = { workspace = true, features = ["derive"] }
tempfile = { workspace = true }
uuid = { workspace = true }

[build-dependencies]
