[package]
name = "relayrl"
version = "0.5.0-rc.1"
authors = ["jrcalgo <jacksonr121@outlook.com>"]
edition = "2024"
description = "A deep reinforcement learning actor-system runtime for concurrent inference and training."
repository = "https://github.com/jrcalgo/relayrl"
documentation = "https://docs.rs/crate/relayrl"
readme = "README.md"
keywords = ["reinforcement", "multi-agent", "multi-actor", "machine-learning", "concurrent"]
categories = ["concurrency", "asynchronous", "science", "simulation", "network-programming"]
license = "Apache-2.0"

[dependencies]
relayrl_framework = { workspace = true }

[features]
default = ["client", "logging-init"]
client = ["relayrl_framework/client"]
metrics = ["relayrl_framework/metrics"]
logging-init = ["relayrl_framework/logging-init"]
tch-backend = ["relayrl_framework/tch-backend"]
profile = ["relayrl_framework/profile"]
